swagger: "2.0"
info:
    title: "Alô Feriado"
    version: "1.0.0"
    description: "Uma API simples que permite cadastrar e consultar feriados"
consumes:
    - "application/json"
produces:
    - "application/json"
paths:
    /feriados/{ibge_code}/{date}/:
        get:
            tags: [Feriados]
            operationId: feriado.fetch
            summary: "Consultar o feriado de uma determinada data de uma região"
            parameters:
                - $ref: "#/parameters/ibge_code"
                - $ref: "#/parameters/date"
            responses:
                200:
                    description: "Exibe o nome do feriado encontrado para a data e região informados"
                    schema:
                        $ref: "#/definitions/Feriado"
                404:
                    description: "Nenhum feriado encontrado para a data e região informados"
parameters:
    ibge_code:
        name: "ibge_code"
        description: "Código do IBGE (referente a uma região)"
        in: path
        type: string
        required: true
        pattern: "^[0-9]{2}$|^[0-9]{7}$"
    date:
        name: "date"
        description: "Data no formato AAAA-MM-DD ou MM-DD"
        in: path
        type: string
        required: true
        pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$|^[0-9]{2}-[0-9]{2}$"
definitions:
    Feriado:
        type: object
        required:
            - name
        properties:
            name:
                type: string
                description: "Nome do feriado"
                example: "Aniversário da cidade de Itajaí"
                minLength: 1
                maxLength: 255
