swagger: "2.0"
info:
    title: "Alô Feriado"
    version: "1.0.0"
    description: "Uma API simples que permite cadastrar e consultar feriados"
consumes:
    - "application/json"
produces:
    - "application/json"
paths:
    /feriados/{ibge_code}/{date}/:
        get:
            tags: [Feriados]
            operationId: feriado.fetch
            summary: "Consultar o feriado de uma determinada data de uma região"
            parameters:
                - $ref: "#/parameters/ibge_code"
                - $ref: "#/parameters/date"
            responses:
                200:
                    description: "Exibe o nome do feriado encontrado para a data e região informados"
                    schema:
                        $ref: "#/definitions/Feriado"
                404:
                    description: "Nenhum feriado encontrado para a data e região informados"
        put:
            tags: [Feriados]
            operationId: feriado.save_municipal_state
            summary: "Registrar feriado de uma determinada data de uma região"
            parameters:
                - $ref: '#/parameters/ibge_code'
                - $ref: '#/parameters/partial_date'
                - $ref: '#/parameters/feriado'
            responses:
                200:
                    description: Feriado atualizado com sucesso
                201:
                    description: Feriado registrado com sucesso
        delete:
            tags: [Feriados]
            operationId: feriado.delete_municipal_state
            summary: "Remover um feriado municipal ou um feriado estadual"
            parameters:
                - $ref: '#/parameters/ibge_code'
                - $ref: '#/parameters/partial_date'
            responses:
                204:
                    description: "Feriado removido com sucesso"
                403:
                    description: "Nao e possivel remover um feriado municipal em um estado ou um feriado estadual em um municipio"
                404:
                    description: "Feriado nao encontrado"
parameters:
    ibge_code:
        name: "ibge_code"
        description: "Código do IBGE (referente a uma região)"
        in: path
        type: string
        required: True
        pattern: "^[0-9]{2}$|^[0-9]{7}$"
    date:
        name: "date"
        description: "Data no formato AAAA-MM-DD ou MM-DD"
        in: path
        type: string
        required: True
        pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
    partial_date:
        name: "date"
        description: "Data no formato MM-DD"
        in: path
        type: string
        required: True
        pattern: "^[0-9]{2}-[0-9]{2}$"
    feriado:
        name: "feriado"
        description: "Feriado para registro"
        in: body
        required: True
        schema:
            type: object
            properties:
                name:
                    type: string
                    description: "Nome do feriado para registro"
definitions:
    Feriado:
        type: object
        required:
            - name
        properties:
            name:
                type: string
                description: "Nome do feriado"
                example: "Aniversário da cidade de Itajaí"
                minLength: 1
                maxLength: 255
