"""empty message

Revision ID: 5ab7484d432f
Revises: 
Create Date: 2020-08-06 07:39:12.358331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab7484d432f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feriados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ibge_code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feriados')
    # ### end Alembic commands ###
